font=jetbrains-mono
color.panel=D5141518
color.border=E8E9EDF2
color.text=FFF4F4F4
color.muted=FFC1C5CA
color.enemy=FFFF535A
color.friend=FF56E18A
color.health=FF52E57D
color.damage=FFFFC447
pixelSnap=true
