font=jetbrains-mono
color.panel=E2111419
color.border=C93A414B
color.text=FFF4F4F4
color.muted=FF9DA5AE
color.enemy=FFFF5964
color.friend=FF54E393
color.health=FF52E57D
color.damage=FFFFC447
pixelSnap=true
