boxMode=FULL
fill=false
healthBar=true
name=true
distance=true
showInvisible=false
lineWidth=1.0
color.enemy=FFFF4D55
color.friend=FF4BE37E
color.fill=20101010
itemLabel=true
armor=true
hardOutline=true
font=jetbrains-mono
